apiVersion: apps/v1
kind: Deployment
metadata:
  name: critterz
spec:
  selector:
    matchLabels:
      app: critterz
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: critterz
    spec:
      containers:
        - name: critterz
          image: '{{ .Values.werf.image.critterz }}'
          workingDir: /app
          env:
            - name: EKP_PLUGIN_ID
              value: 'critterz'
            - name: EKP_PLUGIN_NAME
              value: 'Critterz'
            - name: MORALIS_APP_ID
              value: '{{ .Values.moralis.appId }}'
            - name: MORALIS_SERVER_URL
              value: '{{ .Values.moralis.serverUrl }}'
            - name: REDIS_HOST
              value: 'ekp-redis-master'
          ports:
            - containerPort: 3001
              protocol: TCP
